package overhaul;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *A terminal panel GUI. To best use this, extend this class and override the 
 * process input method.
 */
public class OldTerminalPanelOverhaul extends javax.swing.JPanel
{	
	/**
	 * Creates a new Terminal Panel
	 */
	public OldTerminalPanelOverhaul()
	{
		initComponents();
		
		textArea.setText("Enter a number: \n");
		
		textField.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent ae)
			{	
				String input = textField.getText();
				
				if(input != null)
				{
					textArea.append(input + "\n");
				}
				
				textField.selectAll();
				textArea.setCaretPosition(textArea.getDocument().getLength());
			}
		});
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        textField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setRows(5);
        scrollPane.setViewportView(textArea);

        add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 250));
        add(textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 400, 30));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    protected javax.swing.JTextArea textArea;
    protected javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
